### ISSUE TITLE
When I want to train my dataset,the following bugs apper and how to  solove them?

### ISSUE THREAD

**Issue by 2363959478** [YongWookHa/swin-transformer-ocr#11]
File "C:\Users\23639\.conda\envs\tf2.3\lib\site-packages\x_transformers\x_transformers.py", line 748, in forward
    dots = dots.masked_fill(~input_mask, mask_value)
RuntimeError: The size of tensor a (12) must match the size of tensor b (11) at non-singleton dimension 3

My picture is 280 wide and 32 long.

**Comment by YongWookHa** [comment]
It seems that you need to match the sizes of two tensors at the decoder.
I think you should use a debugger of your code editor and follow the size of the tensors.
The information that you provided is not enought to resolve the error.

Thanks.
