### ISSUE TITLE
how can I get confidence value in predict.py?

### ISSUE THREAD

**Issue by MareArts** [YongWookHa/swin-transformer-ocr#4]
Is there way to get confidence value in prediction?
Thank you.

**Comment by YongWookHa** [comment]
Hi @MareArts .

In `forward`, the decoder generates sequence from encoded image.
https://github.com/YongWookHa/swin-transformer-ocr/blob/9563177f337d465e1750f6d21d002772418db631/models.py#L82

It only returns the result.

So, you need to custom `generate` code of `decoder`. 
Here's where you need to look.

https://github.com/YongWookHa/swin-transformer-ocr/blob/9563177f337d465e1750f6d21d002772418db631/models.py#L162

Good luck!
