### ISSUE TITLE
ONNX deployment

### ISSUE THREAD

**Issue by hjdata11** [YongWookHa/swin-transformer-ocr#6]
swin-transformer를 ONNX로 export 할 때,

TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
RuntimeError: Exporting the operator roll to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.

warining과 함께 에러가 나는데, 혹시 ONNX로 export할 때 문제가 없으셨나요?

**Comment by YongWookHa** [comment]
The traceback says `torch.roll` function is not supported in version 9.

You may need to alter the unsupported operator with supported.

The other task would be handled by pytorch-lightning package.

**Comment by entropy2333** [comment]
> The traceback says `torch.roll` function is not supported in version 9.
> 
> You may need to alter the unsupported operator with supported.
> 
> The other task would be handled by pytorch-lightning package.

According to [issue 3863](https://github.com/onnx/onnx/issues/3863), this problem has been solved in the latest PyTorch. My problem is that the converted ONNX model (6G+) is much larger than PyTorch Model (817MB). Could you offer some suggestions about converting a seq2seq model to ONNX?

**Comment by entropy2333** [comment]
> The traceback says `torch.roll` function is not supported in version 9.
> 
> You may need to alter the unsupported operator with supported.
> 
> The other task would be handled by pytorch-lightning package.

According to [issue 3863](https://github.com/onnx/onnx/issues/3863), this problem has been solved in the latest PyTorch. My problem is that the converted ONNX model (6G+) is much larger than PyTorch Model (817MB). Could you offer any suggestions about converting a seq2seq model to ONNX?

**Comment by IlyasMoutawwakil** [comment]
Hi @entropy2333 , did you find any solution ? I have the same problem and  I think the onnx model is bigger because it's probobaly an unrolled version of the auto regressive transformer.

**Comment by entropy2333** [comment]
> Hi @entropy2333 , did you find any solution ? I have the same problem and I think the onnx model is bigger because it's probobaly an unrolled version of the auto regressive transformer.

Maybe you can refer to https://github.com/Ki6an/fastT5. The specific implementation may still be painful, good luck.
