### ISSUE TITLE
Infrence time, number of parameters and results.

### ISSUE THREAD

**Issue by IlyasMoutawwakil** [YongWookHa/swin-transformer-ocr#8]
Hi and thank you very much for this repo.  I would really appreciate it if you can tell me about how much time this model takes in inference, how much params it contains and if you compared it to other models, which ones did it surpass.

**Comment by YongWookHa** [comment]
Hi @IlyasMoutawwakil.

Thank you for having an interest in this repository.

This repository is easily runnable. You will get a lot of information about this model when you try running/

```
python run.py
```

1. Inference time depends on the machine you're using. And with batch processing, I would say "it is quite fast".
2. with `python run.py`, you will get the model parameter size like below.
```
  | Name    | Type                  | Params
--------------------------------------------------
0 | encoder | CustomSwinTransformer | 6.8 M 
1 | decoder | CustomARWrapper       | 11.1 M
--------------------------------------------------
17.9 M    Trainable params
0         Non-trainable params
17.9 M    Total params
71.621    Total estimated model params size (MB)
```  
4. `swin-transformer` is faster than `visual-transformer` and other `conv` based feature extraction models. And the performance is similar or better.

Have a nice day.
